name: Build and Package Multiple PowerShell Scripts and Create Release

on:
  push:
    branches:
      - dev
      - main
    tags:
      - 'v*.*.*' # Trigger on tags like v1.0.0
  workflow_dispatch:

jobs:
  system_cleanup_build:
    name: Build System Updater
    runs-on: windows-2025

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache PowerShell Modules (Updater)
      uses: actions/cache@v4
      id: cache-psmodules-system
      with:
        path: ~\Documents\WindowsPowerShell\Modules
        key: ${{ runner.os }}-psmodules-system-${{ hashFiles('**/requirements.psd1') }} # Adjust pattern as needed

    - name: Install ps2exe module (Updater)
      if: steps.cache-psmodules-system.outputs.cache-hit != 'true'
      run: |
        pwsh -Command "Install-Module -Name ps2exe -Force"
      shell: pwsh

    - name: Cache Build Tools (Updater)
      uses: actions/cache@v4
      id: cache-buildtools-system
      with:
        path: C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools
        key: ${{ runner.os }}-buildtools-system-2022 # Consider a more dynamic key if needed

    - name: Install Visual Studio Build Tools (Updater)
      if: steps.cache-buildtools-system.outputs.cache-hit != 'true'
      run: |
        # Remove the file if it exists
        if (Test-Path "BuildTools_Full.exe") {
          Remove-Item "BuildTools_Full.exe"
        }
        try {
          Invoke-WebRequest -Uri "https://go.microsoft.com/fwlink/?LinkId=2084274" -OutFile "BuildTools_Full.exe" -ErrorAction Stop
          Write-Host "BuildTools_Full.exe downloaded successfully."
          Start-Process -Wait -FilePath "BuildTools_Full.exe" -ArgumentList "/Quiet", "/InstallSelectableItems", "Microsoft.DesktopBuildTools" -ErrorAction Stop
          Write-Host "Build Tools installed successfully (Direct Download)."
        } catch {
          Write-Warning "Direct download of Build Tools failed: $($_.Exception.Message). Attempting installation via choco..."
          choco install visualstudio2022buildtools -y --package-parameters "--add Microsoft.Component.MSBuild --add Microsoft.Component.VC"
          Write-Host "Build Tools installed successfully (via choco)."
        }
      shell: pwsh

    - name: Set Environment Path (Updater)
      run: |
        $env:PATH += ";C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\*\bin\Hostx64\x64"
      shell: pwsh

    - name: Convert PowerShell script to executable (Updater)
      run: |
        pwsh -Command "ps2exe -InputFile installer.ps1 -OutputFile 'SystemUpdate/installer.exe' -IconFile Refresh.ico -version '1.3'"
      shell: pwsh

    - name: Run mt.exe to embed manifest (Updater)
      run: |
        $mtPath = "C:\Program Files (x86)\Windows Kits\10\bin\10.0.26100.0\x64\mt.exe"
        if (-not (Test-Path $mtPath)) {
          $mtPath = Get-ChildItem "C:\Program Files (x86)\Windows Kits\*\bin\*\x64\mt.exe" -Recurse -ErrorAction SilentlyContinue | Select-Object -First 1 | Select-Object -ExpandProperty FullName
          if (-not $mtPath) {
            Write-Error "mt.exe not found."
            exit 1
          }
        }
        & $mtPath -manifest elevate.manifest.xml -outputresource:"SystemUpdate\Updater.exe";#1
      shell: pwsh

    - name: Create Updater ZIP
      run: |
        Compress-Archive -Path "SystemUpdate\Updater.exe" -DestinationPath "SystemUpdate/updater.zip"
      shell: pwsh

    - name: Upload Artifact (Updater)
      uses: actions/upload-artifact@v4
      with:
        name: SystemCleanUpZIP
        path: SystemCleanUp/SystemCleanUp.zip

  create_release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [system_updater_build]
    if: github.ref_type == 'tag'
    permissions:
      contents: write

    steps:
    - name: Download System updater ZIP Artifact
      uses: actions/download-artifact@v4
      with:
        name: SystemUpdaterZIP

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref_name }}
        files: |
          SystemUpdater.zip
        draft: false
        prerelease: ${{ contains(github.ref_name, '-') }}